services:
  postgresql-17-postgis-3:
    build:
      context: e2e/docker
      dockerfile: postgresql-17-postgis-3.dockerfile
    ports:
      - '17003:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped

  postgresql-16-postgis-3:
    build:
      context: e2e/docker
      dockerfile: postgresql-16-postgis-3.dockerfile
    ports:
      - '16003:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped

  postgresql-15-postgis-3:
    build:
      context: e2e/docker
      dockerfile: postgresql-15-postgis-3.dockerfile
    ports:
      - '15003:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped

  postgresql-14-postgis-3:
    build:
      context: e2e/docker
      dockerfile: postgresql-14-postgis-3.dockerfile
    ports:
      - '14003:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped

  postgresql-13-postgis-3:
    build:
      context: e2e/docker
      dockerfile: postgresql-13-postgis-3.dockerfile
    ports:
      - '13003:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped
